### PR TITLE
make hexer a required dep, remove can-require

### PR DESCRIPTION
**Pull request by Jeloi**
@jcorbin @kriskowal 
I'm not very familiar with this repo. I took out can-require on hexer, and removed logic that was inside conditions on the hexer lib being loaded.
I considered changing the tests to the below lines, which got them passing, but didn't fully understand what I was doing there and the linter complained. Let me know if this is acceptable and what other changes are needed. I've tested with `npm link` and I can now indeed load thriftrw in the browser.

```
        assert.equal(results[3], '00[36m:[0m [31m[1m00[0m                                       [31m[1m.[0m');

        assert.equal(results[6], '00\x1b[36m:\x1b[0m \x1b[31m\x1b[1m00\x1b[0m                                       \x1b[31m\x1b[1m.\x1b[0m');
```

### CODE REVIEW

**Comment by jcorbin** [comment]
lgtm

**Comment by Raynos** [comment]
The optional dependency on `hexer` is to reduce unnecessary footprint.

:-1:

**Comment by jcorbin** [comment]
@Raynos the problem here is that the current is unusable under browserify.  Unless you have a concrete counterproposal for fixing browserify use while maintaining the optional dep, we'll just add the dependency.

**Comment by Raynos** [comment]
@jcorbin 

browserify has this "fun hack feature" where you can replace `require("hexer")` with `(require)("hexer")` and it think it breaks the build step / regex whatevs.

I should double check, but there's definitely aliasing tricks that can be used to confuse browserify.

**Comment by Raynos** [comment]
Ok so turns out `(require)('hexer')` does not work. But:

```
var _require = require;
_require('hexer')
```

does work.

**Comment by Jeloi** [comment]
@jcorbin pinging on this, is this fine to land?

**Comment by jcorbin** [comment]
Yes, go ahead; after it merges, let's ship it in a new minor, v1.3.0

**Comment by vicapow** [comment]
can someone please publish a new version to npm? this is still currently broken

**Comment by dbousque** [comment]
@jcorbin Pinging as well. It would be really nice to have a new release published, I would like to use this project in the browser : it is a dependency of https://github.com/jaegertracing/jaeger-client-node, which I am porting to the browser.

**Pull request merged**
